FROM --platform=linux/amd64 ubuntu:22.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake

COPY . /repo
WORKDIR /repo/colvartools
RUN g++ -o abf_integrate abf_integrate.cpp abf_data.cpp

FROM ubuntu:22.04 as package
COPY --from=builder /repo/colvartools/abf_integrate /
